/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_hubery_testjni_nativethread_CounterNative */

#ifndef _Included_cn_hubery_testjni_nativethread_CounterNative
#define _Included_cn_hubery_testjni_nativethread_CounterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hubery_testjni_nativethread_CounterNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_hubery_testjni_nativethread_CounterNative_nativeSetup_6
  (JNIEnv *, jobject);

/*
 * Class:     cn_hubery_testjni_nativethread_CounterNative
 * Method:    execute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_hubery_testjni_nativethread_CounterNative_nativeExec_6
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
